### ISSUE TITLE
Problems with xbase.testing.typesystem.TypeSystemSmokeTester in the Tycho build

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext-extras#108]
I recently copied the TypeSystemSmokeTester into .xbase.testing (https://github.com/eclipse/xtext-extras/pull/103) then I ported one of my tests (https://github.com/LorenzoBettini/packtpub-xtext-book-2nd-examples/commit/6df01b121e1c26ce3dbd26320c5ecf5b09ebb1e2) to use this version, instead of the one from .xbase.junit (now deprecated).

During the Tycho build, such tests fail with these kinds of wrapped exceptions (a longer log can be found here: https://travis-ci.org/LorenzoBettini/packtpub-xtext-book-2nd-examples/jobs/195956113):

```
195) Error injecting constructor, org.eclipse.emf.common.util.WrappedException: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.<init>(Unknown Source)
  at org.eclipse.xtext.xbase.services.XtypeGrammarAccess.class(Unknown Source)
  while locating org.eclipse.xtext.xbase.services.XtypeGrammarAccess
    for parameter 2 at org.example.xbase.expressions.services.ExpressionsGrammarAccess.<init>(Unknown Source)
  at org.example.xbase.expressions.services.ExpressionsGrammarAccess.class(Unknown Source)
  while locating org.example.xbase.expressions.services.ExpressionsGrammarAccess
  while locating org.eclipse.xtext.IGrammarAccess
    for parameter 1 at org.eclipse.xtext.xbase.validation.UniqueClassNameValidator.register(Unknown Source)
  at org.eclipse.xtext.service.MethodBasedModule.configure(MethodBasedModule.java:57)
  while locating org.eclipse.xtext.xbase.validation.UniqueClassNameValidator
Caused by: org.eclipse.emf.common.util.WrappedException: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadResource(BaseEPackageAccess.java:57)
	at org.eclipse.xtext.parser.BaseEPackageAccess.loadGrammarFile(BaseEPackageAccess.java:44)
```

I found similar stacktraces in the EMF world (https://bugs.eclipse.org/bugs/show_bug.cgi?id=459978 https://bugs.eclipse.org/bugs/show_bug.cgi?id=340094) and the only one related to Xtext https://github.com/xtext/maven-xtext-example/issues/40

Is this related to encoding? Does anyone remember having seen this in the past?

**Comment by LorenzoBettini** [comment]
Some further investigation: if I add `org.eclipse.xtext.xbase.junit` to my test project then the build runs fine, so one guess could be that .xbase.testing does not drag in additional dependencies?

**Comment by cdietrich** [comment]
@LorenzoBettini i cannot reproduce this if i copy and newly generated parent and mydsl pom to your stuff so maybe there is something broken with your target

**Comment by LorenzoBettini** [comment]
@chrdietrich can you please share this?

**Comment by LorenzoBettini** [comment]
@chrdietrich by the way, I'm not talking about the head of my branch (I reverted that commit), I'm referring to that very commit

**Comment by cdietrich** [comment]
well that one gives me [ERROR] Failed to resolve target definition /Users/dietrich/git/packtpub-xtext-book-2nd-examples/org.example.target/neon-xtext-milestones.target: Could not find "org.eclipse.emf.sdk.feature.group/0.0.0" in the repositories of the current location -> [Help 1]

this is why i changed the parent of the xbase example in the first place

**Comment by cdietrich** [comment]
i did some more digging and created this one https://github.com/cdietrich/packtpub-xtext-book-2nd-examples/tree/xxx

**Comment by LorenzoBettini** [comment]
so the failure you get is the same as mine. I haven't tried your code, but on Linux the build fails with the same error...

**Comment by cdietrich** [comment]
ill start a linux vm and give it a try

**Comment by cdietrich** [comment]
hmmm on my linux vm i dont get any problems.
maybe a caching thingy? i cleaned .m2/repo upfront

**Comment by LorenzoBettini** [comment]
On travis you can clear the cache and that will clean the .m2 repository...
later I'll try to do the same on my local machine...
by the way, EMF should be taken from neon site, shouldn't it?

**Comment by cdietrich** [comment]
i dont know.

**Comment by LorenzoBettini** [comment]
By the way, it works also if I simply add `org.eclipse.xtext.junit4` as a dependency of my tests project (no need to add `org.eclipse.xtext.xbase.junit`

**Comment by cdietrich** [comment]
yes  but i assume this pull a bunch of transitive dependencies etc

**Comment by LorenzoBettini** [comment]
indeed that's what I'm trying to figure out...

I tried to explicitly add the deps (not UI related) of .xtext.junit4:

```
 org.eclipse.core.runtime;bundle-version="3.6.0";resolution:=optional;x-installation:=greedy,
 org.eclipse.jdt.launching;bundle-version="3.5.200";resolution:=optional;x-installation:=greedy,
 org.apache.log4j;bundle-version="1.2.15";resolution:=optional,
 org.eclipse.xtend.lib;resolution:=optional,
 org.eclipse.xtext.builder.standalone,
 org.eclipse.emf.codegen.ecore;bundle-version="2.10.2";resolution:=optional,
 org.eclipse.pde.core;resolution:=optional
```

but it still doesn't work... it works only with .xtext.junit4

**Comment by cdietrich** [comment]
maybe the imported packages?

**Comment by LorenzoBettini** [comment]
the differences for imported packages are only a few junit rules additional packages, and if I add them in the tests project nothing changes, it still fails...

**Comment by LorenzoBettini** [comment]
I actually do tests on my machine now (using the profile xexpressions I build only that project)

**Comment by cdietrich** [comment]
can you try my branch?

**Comment by LorenzoBettini** [comment]
I confirm that locally on my machine adding all the required bundles and imported packages fixes the tests.

**Comment by cdietrich** [comment]
hmmm so the question is which is the bad guy

**Comment by LorenzoBettini** [comment]
I'll try to do some tests by removing them one by one.. what worries me is that I first tried with all the non UI bundles and it did not work, so it must be some UI bundle that drags in what's really needed. From what I understand the problem with the EMF parsing might be due to some binary grammar data, could it be?

**Comment by cdietrich** [comment]
have no idea how exactly that reading is done.
since you can reproduce it locally you could do some remote debugging
to see which is the resource thats actually failing parsing.
and whats different when it does not fail

**Comment by cdietrich** [comment]
is is possible noone registers the xtextbin as binary resource (factory)?

**Comment by LorenzoBettini** [comment]
`org.eclipse.xtext.ui` does that the trick, so I'll keep on investigating its deps

**Comment by LorenzoBettini** [comment]
Adding all the required bundles of xtext.ui and import packages DOES NOT work:

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: org.example.xbase.expressions.tests
Bundle-Vendor: My Company
Bundle-Version: 1.0.0.qualifier
Bundle-SymbolicName: org.example.xbase.expressions.tests; singleton:=true
Bundle-ActivationPolicy: lazy
Require-Bundle: org.example.xbase.expressions,
 org.junit;bundle-version="4.7.0",
 org.eclipse.xtext.xbase.lib,
 org.objectweb.asm;bundle-version="[5.0.1,6.0.0)";resolution:=optional,
 org.eclipse.jdt.core,
 org.eclipse.xtext.testing,
 org.eclipse.xtext.xbase.testing,
 org.eclipse.core.runtime;bundle-version="3.4.0";visibility:=reexport,
 org.eclipse.core.resources;bundle-version="3.4.0";visibility:=reexport,
 org.eclipse.ui;bundle-version="3.4.0";visibility:=reexport,
 org.eclipse.ui.editors;bundle-version="3.4.0";visibility:=reexport,
 org.eclipse.jface.text;bundle-version="3.4.0";visibility:=reexport,
 org.eclipse.ui.ide;bundle-version="3.4.0",org.eclipse.xtext;visibility:=reexport,
 org.eclipse.ui.views;bundle-version="3.3.0",
 org.eclipse.emf.edit.ui;bundle-version="2.10.2";visibility:=reexport,
 org.eclipse.ui.workbench.texteditor;bundle-version="3.4.0",
 org.eclipse.xtext.util,
 org.eclipse.jdt.core;bundle-version="3.6.0";resolution:=optional;x-installation:=greedy,
 org.eclipse.core.expressions;bundle-version="3.4.0",
 org.eclipse.search;bundle-version="3.6.0";resolution:=optional;x-installation:=greedy,
 org.eclipse.ltk.core.refactoring;bundle-version="3.5.101";resolution:=optional;visibility:=reexport;x-installation:=greedy,
 org.eclipse.ltk.ui.refactoring;bundle-version="3.4.0";resolution:=optional;x-installation:=greedy,
 org.eclipse.compare;bundle-version="3.5.101";resolution:=optional;x-installation:=greedy,
 org.eclipse.team.core;bundle-version="3.5.101";resolution:=optional;x-installation:=greedy,
 org.eclipse.team.ui;bundle-version="3.5.102";resolution:=optional;x-installation:=greedy,
 org.eclipse.core.filesystem;bundle-version="1.2.1";resolution:=optional;x-installation:=greedy,
 org.eclipse.jdt.launching;bundle-version="3.5.200";resolution:=optional;x-installation:=greedy,
 org.eclipse.xtext.xbase.lib,
 org.eclipse.ui.forms;bundle-version="3.4.1",
 org.eclipse.xtend.lib,
 org.eclipse.jdt.ui;bundle-version="3.6.0";resolution:=optional,
 org.eclipse.xtext.ide;visibility:=reexport
Bundle-RequiredExecutionEnvironment: JavaSE-1.8
Export-Package: org.example.xbase.expressions.tests;x-internal=true
Import-Package: org.hamcrest.core,
 org.junit;version="4.5.0",
 org.junit.runners.model;version="4.5.0",
 org.junit.runner;version="4.5.0",
 org.junit.runners;version="4.5.0",
 org.junit.runner.manipulation;version="4.5.0",
 org.junit.runner.notification;version="4.5.0",
 com.ibm.icu.text;version="4.0.0",
 org.apache.commons.lang,
 org.apache.log4j;version="1.2.15"
```

**Comment by LorenzoBettini** [comment]
So the problem happens only in the maven build and only if the smoketests are executed in the same surefire execution of the other tests: separating the execution of the smoketests from the other tests works: https://github.com/LorenzoBettini/packtpub-xtext-book-2nd-examples/blob/44efd6c7ac5dea2d573bbd09c20a4af37b6e035e/org.example.xbase.expressions.parent/org.example.xbase.expressions.tests/pom.xml
