### ISSUE TITLE
Build does not work without -PuseJenkinsSnapshots=true

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#116]
```
* What went wrong:
Could not resolve all dependencies for configuration ':org.eclipse.xtext.common.types.tests:testCompileClasspath'.
> Could not find org.eclipse.xtext:org.eclipse.xtext.testlanguages:2.12.0-SNAPSHOT.
  Searched in the following locations:
      https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/maven-metadata.xml
      https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.pom
      https://jcenter.bintray.com/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.jar
      file:/home/dietrich/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/maven-metadata.xml
      file:/home/dietrich/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.pom
      file:/home/dietrich/.m2/repository/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.jar
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/maven-metadata.xml
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.pom
      https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.testlanguages/2.12.0-SNAPSHOT/org.eclipse.xtext.testlanguages-2.12.0-SNAPSHOT.jar
  Required by:
      project :org.eclipse.xtext.common.types.tests

* Try:

```

@meysholdt @dhuebner @spoenemann are testlangs not published to oss?

**Comment by spoenemann** [comment]
> are testlangs not published to oss?

Of course not.

**Comment by cdietrich** [comment]
but then building without -PuseJenkinsSnapshots=true makes no sense
cause it always will fail

**Comment by spoenemann** [comment]
Can we eliminate that dependency?

**Comment by cdietrich** [comment]
i think only by copy and pasting the testlangs

**Comment by spoenemann** [comment]
Then that's what we would need to do to solve this issue.

Test languages are part of the tests and thus should not be made public. These inter-repository test dependencies are a leftover of the pre-splitting repository state and indicate that the repositories are not as self-contained as they should be.

**Comment by cdietrich** [comment]
well that would basically mean to copy the test languages to all modules

**Comment by svenefftinge** [comment]
I've removed the deps to `org.eclipse.xtext:org.eclipse.xtext.testlanguages` in all modules from extras and haven't seen any issues (no compile errors nor test failures). 
Am I missing something? Are they used downstream?

**Comment by svenefftinge** [comment]
IF there are dependencies we should look at them and decide if those tests are worth publishing testlanguages or if copying them over would be more beneficial. Generally it is better to have the test data close to the tests.

**Comment by cdietrich** [comment]
i get compile errors on your branch

``` 
/data/xtext-master/git/xtext-extras/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccessTest.java:17: error: package org.eclipse.core.internal.resources does not exist
import org.eclipse.core.internal.resources.ProjectDescription;
                                          ^
/data/xtext-master/git/xtext-extras/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccessTest.java:56: error: cannot find symbol
                ProjectDescription projectDescription = new ProjectDescription();
                ^
  symbol:   class ProjectDescription
  location: class IndexedJvmTypeAccessTest
/data/xtext-master/git/xtext-extras/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/impl/IndexedJvmTypeAccessTest.java:56: error: cannot find symbol
                ProjectDescription projectDescription = new ProjectDescription();
                                                            ^
  symbol:   class ProjectDescription
  location: class IndexedJvmTypeAccessTest
```

**Comment by cdietrich** [comment]
and when fixing this

```
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.addNamespaceDeclarations(XMLSaveImpl.java:900)
	at org.eclipse.emf.ecore.xmi.impl.XMISaveImpl.addNamespaceDeclarations(XMISaveImpl.java:164)
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.traverse(XMLSaveImpl.java:607)
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.save(XMLSaveImpl.java:251)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doSave(XMLResourceImpl.java:389)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.getBytes(AbstractURIHandlerTest.java:101)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.doTest(AbstractURIHandlerTest.java:122)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.testLoadResourceWithPackagedURIs(AbstractURIHandlerTest.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

(calling gradlew build without -PuseJenkinsSnapshot=true (as jenkins does)

**Comment by cdietrich** [comment]
update to the last problem: i get it on master as well => different problem
