### ISSUE TITLE
[J9] Find solution for absense of javax.annotation.Generated

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#207]
```
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelCompleter.addAnnotations(JvmModelCompleter.java:223)
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelCompleter.completeJvmGenericType(JvmModelCompleter.java:188)
        at org.eclipse.xtext.xbase.jvmmodel.JvmModelCompleter.complete(JvmModelCompleter.java:101)
```

**Comment by cdietrich** [comment]
committed a mitigation. we should discuss if we live it by this our find/do any further stuff. what do you think?

**Comment by kthoms** [comment]
I'm fine with that approach. It will work when its on the classpath. Maybe additionally raise an error when generateGenerated is set to true and the class is missing on classpath?

**Comment by cdietrich** [comment]
when configuring the module path to include `java.xml.ws.annotation` e.g. in jdt, then the `@Generated` will be found and added. am still not sure if we should log an error/warning

@szarnekow what do you think?

**Comment by szarnekow** [comment]
I'm on the same page as Karsten. The workaround looks fair enough to me. 
In theory, we could add a preference with the FQN of the to-be-used annotation, but I don't think it would carry its own weight.

**Comment by cdietrich** [comment]
ok i will close for now
