### ISSUE TITLE
Tests: NoClassDefFoundError in AbstractURIHandlerTest: org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-extras#227]
The following NCDFE appears on all subclasses of AbstractURIHandlerTest, e.g. FileInSourceAndPackagedProjectTest:

```
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.addNamespaceDeclarations(XMLSaveImpl.java:900)
	at org.eclipse.emf.ecore.xmi.impl.XMISaveImpl.addNamespaceDeclarations(XMISaveImpl.java:164)
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.traverse(XMLSaveImpl.java:607)
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.save(XMLSaveImpl.java:251)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doSave(XMLResourceImpl.java:389)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.getBytes(AbstractURIHandlerTest.java:101)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.doTest(AbstractURIHandlerTest.java:122)
	at org.eclipse.xtext.resource.uriHell.AbstractURIHandlerTest.testLoadResourceWithPrimaryURIs(AbstractURIHandlerTest.java:145)
```

<img width="710" alt="screenshot 11" src="https://user-images.githubusercontent.com/265597/36092326-494116ec-0fe7-11e8-8aca-ce1c5b00e347.png">

**Comment by cdietrich** [comment]
@kthoms can you set a gralde user home (or mhowever this is called)
to make sure this is not caused by a crapper dependency

**Comment by kthoms** [comment]
I suspect an incomplete test runtime classpath and trying to solve it that way first.

**Comment by kthoms** [comment]
In test SrcSegmentsInUrisAreNotRemovedTests there is an additional NPE:
```
java.lang.ExceptionInInitializerError
	at org.eclipse.emf.ecore.xmi.impl.XMLSaveImpl.addNamespaceDeclarations(XMLSaveImpl.java:900)
[...]
Caused by: java.lang.NullPointerException
	at org.eclipse.emf.ecore.xml.namespace.impl.XMLNamespacePackageImpl.initializePackageContents(XMLNamespacePackageImpl.java:356)
	at org.eclipse.emf.ecore.xml.namespace.impl.XMLNamespacePackageImpl.init(XMLNamespacePackageImpl.java:128)
	at org.eclipse.emf.ecore.xml.namespace.XMLNamespacePackage.<clinit>(XMLNamespacePackage.java:69)
```

**Comment by cdietrich** [comment]
Can you search old issues and Gitter for that message I feel to have a dejavue

**Comment by kthoms** [comment]
Will search for it.
It looks like the XMLTypePackage isn't in the EPackageRegistry yet. But should be done in setUp().

**Comment by cdietrich** [comment]
So you think that’s an order issue ?

**Comment by kthoms** [comment]
Not sure, but I don't think so. Investigating...

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-extras/issues/116
could that be the same problem?

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-core/issues/6

**Comment by kthoms** [comment]
Looks as if this is the same stacktrace. Thanks for the pointer.

**Comment by cdietrich** [comment]
applying the same changes to SrcSegmentsInUrisAreNotRemovedTests as on master did not help?

**Comment by kthoms** [comment]
the test is duplicate, I removed it

**Comment by cdietrich** [comment]
:+1:

**Comment by kthoms** [comment]
Solved by removing duplicate test SrcSegmentsInUrisAreNotRemovedTests
