### ISSUE TITLE
NPE in StandardTypeReferenceOwner

### ISSUE THREAD

**Issue by tivervac** [eclipse/xtext-extras#343]
Had my development environment open and got the following stacktrace while my projects were being build. `redactedFilename.xtend` is an Xtend file that was not open in an editor at the time.

I can not reproduce the error and it did not leave any visible artifacts in the editor

It seems to me that we got given an EObject `context` in the first constructor and that this EObject has no resource attached to it.

Any idea when this can happen?

```
1    [ParallelGenerator-1] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'redactedFilename.xtend'
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.<init>(StandardTypeReferenceOwner.java:46)
	at org.eclipse.xtext.xbase.typesystem.references.StandardTypeReferenceOwner.<init>(StandardTypeReferenceOwner.java:42)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.newTypeReferenceOwner(AbstractXbaseCompiler.java:131)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.getClosureOperationParameterType(XbaseCompiler.java:1769)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.toLambda(XbaseCompiler.java:1796)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:1636)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:355)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.FeatureCallCompiler.prepareExpression(FeatureCallCompiler.java:537)
	at org.eclipse.xtext.xbase.compiler.FeatureCallCompiler._toJavaStatement(FeatureCallCompiler.java:157)
	at org.eclipse.xtext.xbase.compiler.FeatureCallCompiler._toJavaStatement(FeatureCallCompiler.java:296)
	at org.eclipse.xtext.xbase.compiler.FeatureCallCompiler.doInternalToJavaStatement(FeatureCallCompiler.java:112)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:387)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:396)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:351)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:876)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:361)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler._toJavaStatement(XbaseCompiler.java:396)
	at org.eclipse.xtext.xbase.compiler.XbaseCompiler.doInternalToJavaStatement(XbaseCompiler.java:351)
	at org.eclipse.xtend.core.compiler.XtendCompiler.doInternalToJavaStatement(XtendCompiler.java:367)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.internalToJavaStatement(AbstractXbaseCompiler.java:473)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.compile(AbstractXbaseCompiler.java:294)
	at org.eclipse.xtext.xbase.compiler.AbstractXbaseCompiler.compile(AbstractXbaseCompiler.java:274)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.compile(JvmModelGenerator.java:1056)
	at org.eclipse.xtend.core.compiler.XtendGenerator.compile(XtendGenerator.java:213)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateExecutableBody(JvmModelGenerator.java:1033)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateMember(JvmModelGenerator.java:797)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMember(JvmModelGenerator.java:1647)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.lambda$generateMembersInBody$2(JvmModelGenerator.java:292)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.lambda$forEach$0(LoopExtensions.java:38)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.forEach(LoopExtensions.java:40)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMembersInBody(JvmModelGenerator.java:295)
	at org.eclipse.xtend.core.compiler.XtendGenerator.generateMembersInBody(XtendGenerator.java:572)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateBody(JvmModelGenerator.java:269)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateBody(JvmModelGenerator.java:1619)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateMember(JvmModelGenerator.java:743)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMember(JvmModelGenerator.java:1651)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.lambda$generateMembersInBody$2(JvmModelGenerator.java:292)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.lambda$forEach$0(LoopExtensions.java:38)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtext.xbase.compiler.LoopExtensions.forEach(LoopExtensions.java:40)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateMembersInBody(JvmModelGenerator.java:295)
	at org.eclipse.xtend.core.compiler.XtendGenerator.generateMembersInBody(XtendGenerator.java:572)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._generateBody(JvmModelGenerator.java:269)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateBody(JvmModelGenerator.java:1619)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.generateType(JvmModelGenerator.java:226)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator._internalDoGenerate(JvmModelGenerator.java:213)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.internalDoGenerate(JvmModelGenerator.java:1602)
	at org.eclipse.xtext.xbase.compiler.JvmModelGenerator.doGenerate(JvmModelGenerator.java:196)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:95)
	at org.eclipse.xtend.core.compiler.XtendGenerator.doGenerate(XtendGenerator.java:111)
	at org.eclipse.xtext.generator.GeneratorDelegate.doGenerate(GeneratorDelegate.java:43)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:183)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:172)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doGenerate(ParallelBuilderParticipant.java:343)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$1.run(ParallelBuilderParticipant.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=537427 too.

**Comment by tivervac** [comment]
Happened again for the same file.
When it happened I had just rebased our master branch into my branch (just a few seconds ago).
My eclipse was open but had 0 editors open.

I don't see anything to special about the file but I'll report what I can:
- The file has about 1.5k lines of xtend code.
- Most of that (1.3k) is in a private static internal class 
- This internal class has quite a few dispatch functions
- The internal class implements 3 interfaces
- The internal class is annotated with `@FinalFieldsConstructor` and another of our active annotations
- The internal class uses one extension variable and uses a lot of extension methods to this variable

**Comment by cdietrich** [comment]
your AA dont move stuff between files or "steal" their parent?

**Comment by tivervac** [comment]
Our AA isn't that secret. It's the same as org.eclipse.xtext.util.internal.Log with the exception that it doesn't give you an internal API warning.

**Comment by tivervac** [comment]
The `@Log` is present on both the base as the internal class. Having a look at the generated code shows that both loggers are created as expected.

**Comment by cdietrich** [comment]
i wonder if you can remote debug from one eclipse to another to fish for the NPE

**Comment by tivervac** [comment]
Maybe, but it's not very reproducable

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2316

**Comment by szarnekow** [comment]
Christian and I analyzed this today:
We see the NPE because of cached EObject that have been proxified in the meantime. Resource Acaches its resolved types that in turn reference objects from resource B. B was loaded from storage at first, but the builder figures that B needs to be validated so it is loaded from source. Therefore, B is proxified. These proxies survive in the cache of A and are not resolved when obtained from the cache.

**Comment by szarnekow** [comment]
Potential solution:
- `ParameterizedTypeReference.getType()` is made aware of proxies and resolves these - downside: this may happen in the generator in parallel
- The compiler does a resolve if it sees a proxy - downside again: parallel generators
- ????

**Comment by szarnekow** [comment]
Another option that mitigates the problem a little bit:
- Run the generator immediately on the loaded resources and process the next batch afterwards

**Comment by szarnekow** [comment]
Another option:
- Use a derived reference on XClosure to the JvmOperation. Proxy resolution will work automatically.

**Comment by szarnekow** [comment]
Fixed
