### ISSUE TITLE
Investigate sightly increased memory consumption of Java Source Lang with newer jdt

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#363]

**Comment by kthoms** [comment]
Test case `JavaSourceLanguagePerformanceTest#testPerf51200` occasionally failes with timeout 30s. This did not happen before. Observed on JIPP while creating 2.17.0.M2 and on CJE.

**Comment by cdietrich** [comment]
this happens when machines are under heavy load

**Comment by cdietrich** [comment]
@szarnekow i wonder if we can somehow exclude the creation of the test models from the timeout time

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" tests="10" skipped="0" failures="1" errors="0" timestamp="2019-02-06T17:54:38" hostname="hipp3" time="58.273">
  <properties/>
  <testcase name="testPerf00100" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.399"/>
  <testcase name="testPerf00200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.409"/>
  <testcase name="testPerf00400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.495"/>
  <testcase name="testPerf00800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.717"/>
  <testcase name="testPerf01600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.145"/>
  <testcase name="testPerf03200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.953"/>
  <testcase name="testPerf06400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="3.138"/>
  <testcase name="testPerf12800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="6.274"/>
  <testcase name="testPerf25600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="12.959"/>
  <testcase name="testPerf51200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="30.78">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.lang.Object.notifyAll(Native Method)
	at java.lang.ref.ReferenceQueue.enqueue(ReferenceQueue.java:75)
	at java.lang.ref.Reference.enqueue(Reference.java:296)
	at org.eclipse.emf.common.util.URI$LazyFragmentInitializer.&lt;init&gt;(URI.java:5459)
	at org.eclipse.emf.common.util.URI.appendFragment(URI.java:5492)
	at org.eclipse.xtext.common.types.access.binary.asm.BinaryObjectTypeSignature.getURI(BinaryObjectTypeSignature.java:50)
	at org.eclipse.xtext.common.types.access.binary.asm.Proxies.createProxy(Proxies.java:161)
	at org.eclipse.xtext.common.types.access.binary.asm.Proxies.createTypeReference(Proxies.java:98)
	at org.eclipse.xtext.common.types.access.binary.asm.JvmDeclaredTypeBuilder.setSuperTypes(JvmDeclaredTypeBuilder.java:153)
	at org.eclipse.xtext.common.types.access.binary.asm.JvmDeclaredTypeBuilder.visit(JvmDeclaredTypeBuilder.java:121)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:524)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at org.eclipse.xtext.common.types.access.binary.asm.JvmDeclaredTypeBuilder.buildType(JvmDeclaredTypeBuilder.java:70)
	at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.lambda$installFull$3(JavaDerivedStateComputer.java:244)
	at org.eclipse.xtext.java.resource.JavaDerivedStateComputer$$Lambda$12/806762674.acceptResult(Unknown Source)
	at org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:588)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:475)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.xtext.java.resource.JavaDerivedStateComputer.installFull(JavaDerivedStateComputer.java:260)
	at org.eclipse.xtext.java.resource.JavaResource.lambda$installFull$1(JavaResource.java:195)
	at org.eclipse.xtext.java.resource.JavaResource$$Lambda$11/1870312919.apply(Unknown Source)
	at org.eclipse.xtext.java.resource.JavaResource.initializing(JavaResource.java:205)
	at org.eclipse.xtext.java.resource.JavaResource.installFull(JavaResource.java:199)
	at org.eclipse.xtext.java.resource.JavaResource.getContents(JavaResource.java:168)
	at org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest.doTestPerformance(JavaSourceLanguagePerformanceTest.java:94)
	at org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest.testPerf51200(JavaSourceLanguagePerformanceTest.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
</failure>
  </testcase>
  <system-out><![CDATA[100 file took 264 ms
200 file took 268 ms
400 file took 378 ms
800 file took 475 ms
1600 file took 825 ms
3200 file took 1457 ms
6400 file took 2271 ms
12800 file took 4743 ms
25600 file took 9653 ms
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" tests="10" skipped="0" failures="0" errors="0" timestamp="2019-02-06T10:21:42" hostname="oss-jenkins-c468b76b8-hz7tn" time="43.949">
  <properties/>
  <testcase name="testPerf00100" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.099"/>
  <testcase name="testPerf00200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.319"/>
  <testcase name="testPerf00400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.493"/>
  <testcase name="testPerf00800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.715"/>
  <testcase name="testPerf01600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.839"/>
  <testcase name="testPerf03200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.601"/>
  <testcase name="testPerf06400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="2.617"/>
  <testcase name="testPerf12800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="4.384"/>
  <testcase name="testPerf25600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="9.21"/>
  <testcase name="testPerf51200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="22.666"/>
  <system-out><![CDATA[100 file took 373 ms
200 file took 212 ms
400 file took 367 ms
800 file took 466 ms
1600 file took 649 ms
3200 file took 1147 ms
6400 file took 1818 ms
12800 file took 3219 ms
25600 file took 7161 ms
51200 file took 18186 ms
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

```

maybe the test model creation takes disproportional time on slower machines

**Comment by cdietrich** [comment]
with slightly inc timeout on ci.eclipse.org

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" tests="10" skipped="0" failures="0" errors="0" timestamp="2019-02-06T18:55:29" hostname="hipp3" time="52.415">
  <properties/>
  <testcase name="testPerf00100" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.319"/>
  <testcase name="testPerf00200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.358"/>
  <testcase name="testPerf00400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.47"/>
  <testcase name="testPerf00800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="0.753"/>
  <testcase name="testPerf01600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.073"/>
  <testcase name="testPerf03200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="1.621"/>
  <testcase name="testPerf06400" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="3.035"/>
  <testcase name="testPerf12800" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="5.627"/>
  <testcase name="testPerf25600" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="11.398"/>
  <testcase name="testPerf51200" classname="org.eclipse.xtext.java.tests.JavaSourceLanguagePerformanceTest" time="26.758"/>
  <system-out><![CDATA[100 file took 493 ms
200 file took 240 ms
400 file took 335 ms
800 file took 550 ms
1600 file took 721 ms
3200 file took 1150 ms
6400 file took 2132 ms
12800 file took 4251 ms
25600 file took 8579 ms
51200 file took 20593 ms
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

**Comment by cdietrich** [comment]
=> margin quite small

**Comment by szarnekow** [comment]
Yes, that should be possible if we rewrite the test case to a parameterized test. In that case, file creation could happen in the setup.

**Comment by cdietrich** [comment]
Closed as wont-fix. Feel free to reopen at github.com/eclipse/xtext
