### ISSUE TITLE
[Xbase] BigInteger Literals are broken at runtime

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#40]
`1.23e123bi` compiles to`new BigInteger("1.23").multiply(BigInteger.TEN.pow(123))`
which leads to following exception at runtime

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "1.23"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.math.BigInteger.<init>(BigInteger.java:461)
    at java.math.BigInteger.<init>(BigInteger.java:597)
```

**Comment by cdietrich** [comment]
i propose this generation pattern

```
new BigDecimal("1.23").multiply(BigDecimal.TEN.pow(45)).toBigInteger()
```

**Comment by kthoms** [comment]
Should work that way

**Comment by cdietrich** [comment]
please review
