### ISSUE TITLE
Inconsistent handling of synthetic fragment for missing obj 

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext-extras#695]
In `BatchLinkableResourceStorageWritable` a "none" fragment is used to probably mark a missing unresolved EObject. Which is fine I think:

https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.java#L158

Later on in `BatchLinkableResourceStorageLoadable` one try to resolve the EObject using the fragment "none" which leads to a null key entry in the `targetToSourceMap` 

https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.java#L87

The bad thing about, is that the `BatchLinkableResourceStorageWritable` uses `targetToSourceMap` to write an association map and fails with an NullPointerException inside the `logIfResourceMismatch` because of the `null` key:
https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.java#L144

Because of that NPE an Xtend resource can not be loaded/indexed. 

The problem with this synthetic fragment string seem to be old and I'm not sure why it now breaks the build. Probably because of migration from Xtend -> Java and new try{}finally{} replacement. 

I see two possible actions:
1. Guard  `BatchLinkableResourceStorageWritable.logIfResourceMismatch` for `null` object
2. Don't produce `null` key by checking for the "none" fragment or better for the `getFragment(keyObject) == null` see  BatchLinkableResourceStorageLoadable.readAssociationsAdapter(BatchLinkableResource, ZipInputStream)

**Comment by dhuebner** [comment]
@szarnekow 
Does it make sense?

**Comment by szarnekow** [comment]
The analysis sounds about right to me. It would be great to have a reproducer.

**Comment by dhuebner** [comment]
@szarnekow 
Create a reproducer is harder than I expected. It turned out that the EObject that I mentioned here:
>  a "none" fragment is used to probably mark a missing unresolved EObject. Which is fine I think:

... is a synthetic constructor for an Xtend class that is annotated with a `@FinalFieldsConstructor` annotation and the bogus case here is that this JvmConstructor doesn't have an EContainer :-/ 


> Which is fine I think

I don't think it is fine to handle orphaned EObject in `BatchLinkableResourceStorageWritable` 

I'm not sure how to proceed here, just handle the "none" fragment case would solve the Xtend loading problem but will not point to the real problem.

**Comment by dhuebner** [comment]
@szarnekow 
My PR demonstrates the bogus behavior
Please let me know if that is enough as a reproducer

**Comment by dhuebner** [comment]
@cdietrich @szarnekow 
I would like to propose to reduce the log level back to debug. I have around 200 error log entries in a huge Xtend workspace during a clean build. WDYT?

**Comment by cdietrich** [comment]
i have found this one

```
clipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmCommon.xtend'.
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.logIfResourceMismatch(BatchLinkableResourceStorageWritable.java:144)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.lambda$writeAssociationMap$1(BatchLinkableResourceStorageWritable.java:137)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeAssociationMap(BatchLinkableResourceStorageWritable.java:136)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeAssociationsAdapter(BatchLinkableResourceStorageWritable.java:130)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable.writeEntries(BatchLinkableResourceStorageWritable.java:56)
	at org.eclipse.xtext.resource.persistence.ResourceStorageWritable.writeResource(ResourceStorageWritable.java:45)
	at org.eclipse.xtext.resource.persistence.ResourceStorageFacade.saveResource(ResourceStorageFacade.java:97)
	at org.eclipse.xtext.builder.BuilderParticipant.saveResourceStorage(BuilderParticipant.java:682)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:182)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.handleChangedContents(ParallelBuilderParticipant.java:173)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant.doGenerate(ParallelBuilderParticipant.java:351)
	at org.eclipse.xtext.builder.ParallelBuilderParticipant$1.run(ParallelBuilderParticipant.java:316)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	```

(from before your logging)

**Comment by dhuebner** [comment]
@cdietrich 
Where? Maybe the old state with "none" entries was loaded? After a clean build this should not be logged

**Comment by cdietrich** [comment]
@dhuebner its from weeks ago. so the question would still be what causes this.

**Comment by dhuebner** [comment]
@cdietrich 
From what I see in logs it's only the JvmConstructor and only from Xtend classes annotated with an active annotations. The JvmConstructor (default) is a synthetic one, I'm not sure where it is added. So it could be something we do wrong in the annotation processing regarding the handling of synthetic Jvm objects. The good thing is that I can reproduce it easily, even during dummy editing in an editor.

![Mar-18-2021 13-17-31](https://user-images.githubusercontent.com/454322/111624756-61562800-87ec-11eb-9c18-a08d563d4b6a.gif)

I also created an issue for investigating the cause: eclipse/xtext-xtend/issues#1189

**Comment by dhuebner** [comment]
However the example above is just to show how a "none" fragment comes into the map, it doesn't reproduce the more complex NPE scenario where the date read from the map and written back causing an NPE. I hope it not related to the parallel build...

**Comment by cdietrich** [comment]
see also https://stackoverflow.com/questions/68682533/maven-builds-multi-module-project-succesfully-eclipse-shows-errors/68699217#68699217

**Comment by cdietrich** [comment]
HoverTest (at least called from tycho)
logs

```
2021-08-17T15:06:03.7960697Z Running org.eclipse.xtext.example.domainmodel.ui.tests.HoverTest
2021-08-17T15:06:03.9353564Z 0    [main] ERROR org.eclipse.xtext.xbase.resource.BatchLinkableResourceStorageWritable  - Object (JvmParameterizedTypeReference: java.lang.String) is not contained in any resource
2021-08-17T15:06:03.9365700Z 
```

**Comment by cdietrich** [comment]
here the problem is that
org.eclipse.xtext.example.domainmodel.jvmmodel.DomainmodelJvmModelInferrer.removeDuplicateGettersSetters(JvmDeclaredType)
seems to remove the container

**Comment by cdietrich** [comment]
org.eclipse.xtend.core.macro.declaration.JvmTypeDeclarationImpl.addConstructor(Procedure1<MutableConstructorDeclaration>) removes old constructor.
so i assume it will create orphans too.

**Comment by cdietrich** [comment]
chaning to

```
	def addConstructor(Procedure1<MutableConstructorDeclaration> initializer) {
		checkMutable
		Preconditions.checkArgument(initializer !== null, "initializer cannot be null")
		// remove default constructor
		val constructor = delegate.members.filter(JvmConstructor).findFirst[compilationUnit.typeExtensions.isSingleSyntheticDefaultConstructor(it)]
		if (constructor !== null) {
			val src = compilationUnit.jvmModelAssociations.getPrimarySourceElement(constructor.declaringType)
			compilationUnit.jvmModelAssociator.removeAssociation(src, constructor)
			EcoreUtil.remove(constructor)
		}
```

with the updated removeAssociation from above also seems to work.

**Comment by cdietrich** [comment]
looks like i have a solution for the constructor problem.

**Comment by cdietrich** [comment]
Problem fixed in domain model example and Xtend.
enhanced removeAssociation

@dhuebner are you ok with closing?
