### ISSUE TITLE
StandaloneBuilderTest flaky/does not work on Linux

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#814]
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.xtext.builder.standalone.StandaloneBuilderTest.testWriteStorageResource(StandaloneBuilderTest.java:90)
```
```
0    [main] INFO  uilder.standalone.StandaloneBuilder  - Collecting source models.
178  [main] INFO  uilder.standalone.StandaloneBuilder  - Validate and generate.
184  [main] INFO  uilder.standalone.StandaloneBuilder  - Validating: 'Bar.buildertestlanguage'
266  [main] INFO  uilder.standalone.StandaloneBuilder  - Validating: 'Foo.buildertestlanguage'
267  [main] INFO  uilder.standalone.StandaloneBuilder  - Starting generator for input: 'Bar.buildertestlanguage'
308  [main] INFO  uilder.standalone.StandaloneBuilder  - Starting generator for input: 'Foo.buildertestlanguage'
311  [main] INFO  uilder.standalone.StandaloneBuilder  - Build took 313ms.

```

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.xtext.builder.standalone.StandaloneBuilderTest.testDifferentOutputFolders(StandaloneBuilderTest.java:73)
```
```
0    [main] INFO  uilder.standalone.StandaloneBuilder  - Collecting source models.
171  [main] INFO  uilder.standalone.StandaloneBuilder  - Validate and generate.
176  [main] INFO  uilder.standalone.StandaloneBuilder  - Validating: 'Bar.buildertestlanguage'
243  [main] INFO  uilder.standalone.StandaloneBuilder  - Validating: 'Foo.buildertestlanguage'
244  [main] INFO  uilder.standalone.StandaloneBuilder  - Starting generator for input: 'Bar.buildertestlanguage'
258  [main] INFO  uilder.standalone.StandaloneBuilder  - Starting generator for input: 'Foo.buildertestlanguage'
259  [main] INFO  uilder.standalone.StandaloneBuilder  - Build took 261ms.

```

**Comment by cdietrich** [comment]
![Bildschirmfoto_2022-10-01_10-07-51](https://user-images.githubusercontent.com/238736/193399593-f8da885a-6311-48ef-bea8-976d8d9d02de.png)
both files seem to go to same target dir

**Comment by cdietrich** [comment]
org.eclipse.xtext.builder.standalone.StandaloneBuilder.registerCurrentSource(URI)
seems to missbehave

file:/home/dietrich/xtext-master/git/xtext-extras/org.eclipse.xtext.builder.standalone.tests/test-data/standalone/src2/Bar.buildertestlanguage -> src2
file:/home/dietrich/xtext-master/git/xtext-extras/org.eclipse.xtext.builder.standalone.tests/test-data/standalone/src/Foo.buildertestlanguage -> src2

**Comment by cdietrich** [comment]
@szarnekow  now https://ci.eclipse.org/xtext/job/xtext-maven/job/cd_fixBugs/ is red

**Comment by cdietrich** [comment]
org.eclipse.xtext.maven.plugin/target/test-classes/it/generate/output-per-goal[cd_fixBugs] > find . -name "*.class"
./target/test-classes/SimpleTestClassXbase.class
./target/classes/SimpleClassXbase.class
./target/xtext-temp/stub-classes/SimpleClassXbase.class
./target/xtext-temp/stub-classes/SimpleTestClassXbase.class

**Comment by cdietrich** [comment]
in eclipse org.eclipse.xtext.builder.standalone.StandaloneBuilderTest.testDuplicateSourceEntries
also fails
