### ISSUE TITLE
Fix JavaResource 

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-extras#92]
The Changes to Java Resource in https://github.com/eclipse/xtext-extras/commit/11386fcc848450f436dee0da528b7c8355d2027b

make tests in xtext-xtend fail (e.g. XtendIncrementalBuilderTest)
and make the build of xtext-extras itself fail

```
Caused by: java.lang.NullPointerException
        at org.eclipse.xtext.common.types.access.impl.AbstractClassMirror.getEObject(AbstractClassMirror.java:69)
        at org.eclipse.xtext.common.types.access.TypeResource.getEObject(TypeResource.java:90)
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
        at org.eclipse.xtext.common.types.access.impl.IndexedJvmTypeAccess.getIndexedJvmType(IndexedJvmTypeAccess.java:79)
        at org.eclipse.xtext.common.types.access.impl.IndexedJvmTypeAccess.getIndexedJvmType(IndexedJvmTypeAccess.java:69)
        at org.eclipse.xtext.java.resource.JavaResource.resolveJavaObjectURIProxy(JavaResource.java:189)
        at org.eclipse.xtext.common.types.impl.JvmAnnotationValueImplCustom.eResolveProxy(JvmAnnotationValueImplCustom.java:22)
        at org.eclipse.xtext.common.types.impl.JvmAnnotationValueImpl.getOperation(JvmAnnotationValueImpl.java:78)
        at org.eclipse.xtext.common.types.impl.JvmAnnotationValueImpl.eGet(JvmAnnotationValueImpl.java:134)
        at org.eclipse.xtext.common.types.impl.JvmBooleanAnnotationValueImpl.eGet(JvmBooleanAnnotationValueImpl.java:94)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
        at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
        at org.eclipse.emf.ecore.util.EContentsEList$FeatureIteratorImpl.hasNext(EContentsEList.java:439)
        at org.eclipse.xtext.EcoreUtil2.resolveCrossReferences(EcoreUtil2.java:518)
        at org.eclipse.xtext.EcoreUtil2.resolveAll(EcoreUtil2.java:487)
        at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:500)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:224)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:86)
        at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
        at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:617)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterables.addAll(Iterables.java:352)
        at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:89)
        at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:56)
        at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:248)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:419)
        at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:400)
        at org.xtext.gradle.builder.XtextGradleBuilder.doBuild(XtextGradleBuilder.java:360)
        at org.xtext.gradle.builder.XtextGradleBuilder.build(XtextGradleBuilder.java:206)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:149)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
```

**Comment by cdietrich** [comment]
http://services.typefox.io/open-source/jenkins/job/xtext-extras/job/master/127/console

**Comment by cdietrich** [comment]
@svenefftinge @spoenemann it seems we have killed ourselves here bootstrapping wise

**Comment by cdietrich** [comment]
i assume we could do something like

```
val fragment = proxy.eProxyURI.fragment
        				var result = access.getIndexedJvmType(if (fragment === null || fragment.contains("()")) proxy.eProxyURI().trimFragment else proxy.eProxyURI(), getResourceSet());
        				
```
but i am not sure if this in the right way for this.

**Comment by kthoms** [comment]
This would fix 4 of 6 test cases. The issues remaining are:
```
xtend.core.tests.fast (xtend)
org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest
testSimpleMixedBuild_02(org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest)
java.lang.AssertionError: [ERROR:The field MyClass.a refers to the missing type Object (inmemory:/src/MyFile.xtend line : 3 column : 17)]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest.testSimpleMixedBuild_02(XtendIncrementalBuilderTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

testSimpleMixedBuild_03(org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest)
java.lang.AssertionError: [ERROR:The method or field myClass is undefined for the type A (inmemory:/src/MyFile.xtend line : 4 column : 31), ERROR:The field MyClass.a refers to the missing type Object (inmemory:/src/MyFile.xtend line : 3 column : 17), ERROR:The field MyClass.a refers to the missing type Object (inmemory:/src/MyFile.xtend line : 5 column : 30)]
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.eclipse.xtend.core.tests.build.XtendIncrementalBuilderTest.testSimpleMixedBuild_03(XtendIncrementalBuilderTest.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.eclipse.xtext.testing.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.run(CoreTestApplication.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by cdietrich** [comment]
Well then I assume we need a completely different solution for the annotation issue

**Comment by cdietrich** [comment]
or we do the op check twice

```
try {
        				val fragment = proxy.eProxyURI.fragment
        				val isOp = fragment === null || fragment.contains("()")
        				var result = access.getIndexedJvmType(if (isOp) proxy.eProxyURI().trimFragment else proxy.eProxyURI(), getResourceSet());
        				if (result instanceof JvmDeclaredType && isOp) {
        				    result = new JavaFragmentProvider().getEObject(result.eResource, proxy.eProxyURI.fragment, new Fallback() {
                                override getEObject(String fragment) {
                                    return null;
                                }
                                
                                override getFragment(EObject obj) {
                                    return null;
                                }
                            });
                            if (result !== null)
        					   return result;
        				} else if (result !== null) {
        					return result;
        				}
        			} catch(UnknownNestedTypeException e) {
        				return proxy;
        			}
```

**Comment by svenefftinge** [comment]
Thanks @cdietrich for investigation. I went with special handling for operation fragments as a holistic solution doesn't seem feasible without too many changes in the common types part.
I pushed directly to master, since the build is broken atm anyway. Also I reverted miro's the bootstrapping merge, so we hopefully have a  snapshot version that works again.
